services:

  db:
    image: postgres:latest
    container_name: coderr_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql

  web:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file: .env
    container_name: coderr_backend
    restart: unless-stopped
    volumes:
      - .:/app
      - coderr_media:/app/media
      - coderr_static:/app/static
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: coderr_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - coderr_media:/app/media:ro
      - coderr_static:/app/static:ro
    depends_on:
      - web




volumes:
  postgres_data:
  coderr_media:
  coderr_static:
