services:

  db:
    image: postgres:18
    container_name: coderr_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file: .env
    container_name: coderr_backend
    restart: unless-stopped
    volumes:
      - .:/app
      - coderr_media:/app/media
      - coderr_static:/app/static
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy




volumes:
  postgres_data:
  coderr_media:
  coderr_static:
