# Generated by Django 6.0.1 on 2026-02-05 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles_app', '0004_remove_profile_email_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_delivery_time', models.PositiveIntegerField(help_text='Maximale Lieferzeit in Tagen')),
                ('ordering', models.CharField(choices=[('asc', 'Aufsteigend'), ('desc', 'Absteigend')], default='asc', max_length=20)),
                ('search', models.CharField(blank=True, help_text='Suchbegriff für die Angebotssuche', max_length=255)),
                ('page_size', models.PositiveIntegerField(help_text='Anzahl der Angebote pro Seite')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offer_images/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.TextField(blank=True)),
                ('userdetails', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='profiles_app.profile')),
            ],
        ),
    ]
