# Generated by Django 6.0.1 on 2026-02-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_remove_offer_details_offerdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='max_delivery_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='page_size',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='price',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='search',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='userdetails',
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(default=list),
        ),
    ]
