# Generated by Django 6.0.1 on 2026-02-10 12:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('business_profile_count', models.PositiveIntegerField(default=0)),
                ('offer_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
