# Generated by Django 6.0.1 on 2026-02-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_info_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseInfo',
        ),
    ]
