# Generated by Django 6.0.1 on 2026-02-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0004_remove_profile_email_remove_profile_first_name_and_more'),
        ('reviews_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('business', 'reviewer')},
        ),
    ]
