# Generated by Django 6.0.1 on 2026-02-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='profile_pictures/'),
            preserve_default=False,
        ),
    ]
