# Generated by Django 6.0.1 on 2026-02-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0003_alter_profile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
